# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c66895b5c76e45e20092e36cbf85b239105c9201701169998861f8798ef36c2f2756dd4687f855e8eaa96eb475f489850c4a955772cb134afef5a3f1ca6e83ba

test:
  secret_key_base: 7e8c25634fcdb2513ca0f960ea688c4090d5be82e25e9d8e6ada01b7dec9485078997226475321d1392c0733fe1b407ae3075139ef560d031d4882af06e3683c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
